[package]
name = "relay_pe"
version = "0.1.0"
authors = ["Jared Roesch <jroesch@octoml.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
